 README.md                                        |    4 [32m+[m[31m-[m
 configs/README.md                                |    2 [32m+[m
 configs/templates/tutorial.acg                   |    8 [32m+[m[31m-[m
 documentation/developer_guide/00_architecture.md |   29 [32m++[m[31m--[m
 documentation/developer_guide/01_potentials.md   |   12 [32m+[m[31m-[m
 documentation/developer_guide/02_topology.md     |    7 [32m+[m[31m-[m
 documentation/developer_guide/03_compute.md      |   44 [32m++++[m[31m--[m
 documentation/developer_guide/04_mpi_runtime.md  |   43 [32m+++[m[31m---[m
 documentation/developer_guide/08_schedulers.md   |   16 [32m+[m[31m-[m
 documentation/developer_guide/09_workflows.md    |   47 [32m+++++[m[31m-[m
 documentation/developer_guide/10_vp_grower.md    |  229 [32m++++++++++++++[m[31m---------------[m
 documentation/developer_guide/11_io_utilities.md |   36 [32m++++[m[31m-[m
 pyproject.toml                                   |    6 [32m+[m
 src/AceCG/PACKAGE_STRUCTURE.md                   |   22 [32m++[m[31m-[m
 src/AceCG/__init__.py                            |    5 [32m+[m
 src/AceCG/analysis/__init__.py                   |    2 [32m+[m
 src/AceCG/analysis/rdf.py                        |   71 [32m+++[m[31m------[m
 src/AceCG/compute/__init__.py                    |   15 [32m++[m
 src/AceCG/compute/frame_geometry.py              |    8 [32m+[m[31m-[m
 src/AceCG/compute/mpi_engine.py                  |  692 [32m++++++++++++++++++++++++++++++++++++++++++[m[31m---------------------------------------------[m
 src/AceCG/compute/reducers.py                    |  286 [32m++++++++++++++++++++++++++[m[31m----------[m
 src/AceCG/compute/vp_prepare.py                  |  203 [31m--------------------------[m
 src/AceCG/configs/__init__.py                    |   17 [32m++[m[31m-[m
 src/AceCG/configs/models.py                      |   20 [32m++[m[31m-[m
 src/AceCG/configs/parser.py                      |  286 [32m+++++++++++++++++++++++++++++[m[31m-------[m
 src/AceCG/configs/vp_growth_config.py            |   11 [32m+[m[31m-[m
 src/AceCG/fitters/__init__.py                    |    9 [32m+[m[31m-[m
 src/AceCG/fitters/base.py                        |    8 [32m+[m[31m-[m
 src/AceCG/fitters/fit_bspline.py                 |  122 [32m+++++++++++++++[m[31m-[m
 src/AceCG/fitters/fit_harmonic.py                |   12 [32m+[m[31m-[m
 src/AceCG/fitters/fit_multi_gaussian.py          |   12 [32m+[m[31m-[m
 src/AceCG/io/__init__.py                         |   32 [32m+++[m[31m-[m
 src/AceCG/io/coordinates.py                      |  187 [32m++++++++++++++++++++++[m[31m--[m
 src/AceCG/io/coordinates_writers.py              |   17 [32m++[m[31m-[m
 src/AceCG/io/forcefield.py                       |  411 [32m+++++++++++++++++++++++++++++++++++++++++++[m[31m---------[m
 src/AceCG/io/tables.py                           |  674 [32m+++++++++++++++++++++++++++++++++++++++++++++++++++++++++[m[31m---------------------------[m
 src/AceCG/io/trajectory.py                       | 1094 [32m++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[m[31m---[m
 src/AceCG/io/vp_ffbuilder.py                     |   94 [32m+++++++++[m[31m---[m
 src/AceCG/optimizers/__init__.py                 |    3 [32m+[m[31m-[m
 src/AceCG/potentials/__init__.py                 |    1 [32m+[m
 src/AceCG/potentials/base.py                     |    5 [32m+[m[31m-[m
 src/AceCG/samplers/_lammps_script.py             |   20 [32m++[m[31m-[m
 src/AceCG/samplers/base.py                       |  106 [32m++++++++++++[m[31m--[m
 src/AceCG/schedulers/mpi_backend.py              |   57 [32m+++[m[31m-----[m
 src/AceCG/schedulers/task_runner.py              |    2 [32m+[m
 src/AceCG/topology/__init__.py                   |   18 [32m+++[m
 src/AceCG/topology/neighbor.py                   |  184 [32m+++++++++++++++++++++[m[31m--[m
 src/AceCG/topology/topology_array.py             |   20 [32m++[m[31m-[m
 src/AceCG/topology/types.py                      |   20 [32m++[m[31m-[m
 src/AceCG/workflows/__init__.py                  |   81 [32m+++++++[m[31m----[m
 src/AceCG/workflows/base.py                      |   60 [32m++++++[m[31m--[m
 src/AceCG/workflows/fm.py                        |   80 [32m++++++++[m[31m--[m
 src/AceCG/workflows/sampling.py                  |   63 [32m++++[m[31m----[m
 src/AceCG/workflows/vp_growth.py                 |  446 [32m++++++++[m[31m------------------------------------------------[m
 tests/conftest.py                                |    6 [32m+[m[31m-[m
 tests/test_analysis_rdf.py                       |  157 [32m++++++++++++++++++++[m
 tests/test_compute_new.py                        |  329 [32m++++++++++++++++++++++++++[m[31m---------------[m
 tests/test_config_mask_parser.py                 |  581 [32m++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[m[31m-[m
 tests/test_force_accumulation.py                 |    4 [32m+[m[31m-[m
 tests/test_import_graph.py                       |   31 [32m+++[m[31m-[m
 tests/test_io_forcefield.py                      |  266 [32m++++++++++++++++++++++++[m[31m----------[m
 tests/test_io_tables.py                          |   73 [32m++++++++++[m
 tests/test_mpi_engine_topology_context.py        |  237 [32m+++++++++++++++++++++++++++[m[31m---[m
 tests/test_one_pass_engine.py                    |  480 [32m+++++++++++++++++++++++++++++++++++++++++++++++++++++++++[m[31m---[m
 tests/test_potential_derivatives.py              |  242 [32m++++++++++++++++++++++++++++++[m[31m-[m
 tests/test_samplers_contract.py                  |  112 [32m+++++++++++++[m[31m-[m
 tests/test_sampling_rem_workflow.py              |   90 [32m++++++++++++[m
 tests/test_scheduler_resource_pool.py            |   75 [32m++++[m[31m------[m
 tests/test_task_runner_post_exec.py              |   38 [32m+++++[m
 tests/test_u4_rem_engine.py                      |    6 [32m+[m[31m-[m
 tests/test_u6_cdfm_engine.py                     |   48 [32m++++[m[31m--[m
 tests/test_vp_ffbuilder.py                       |   26 [32m++++[m
 tests/test_vp_growth_config.py                   |   31 [32m++++[m
 tests/test_vp_growth_mpi.py                      |  321 [32m++++++++++++++++++++++++++++[m[31m------------[m
 tests/test_vp_growth_workflow.py                 |   90 [32m++++++++[m[31m----[m
 tests/test_vp_prepare.py                         |  185 [31m-----------------------[m
 76 files changed, 6928 insertions(+), 2459 deletions(-)
